[[redirects]]
  from = "/api/*"
  to   = "https://ca8f7c19b578.ngrok-free.app/api/:splat"
  status = 200

[[redirects]]
  from = "/lex/*"
  to   = "https://ca8f7c19b578.ngrok-free.app/lex/:splat"
  status = 200

[[redirects]]
  from = "/teacher/*"
  to   = "https://ca8f7c19b578.ngrok-free.app/teacher/:splat"
  status = 200

[[redirects]]
  from = "/continuum/*"
  to   = "https://ca8f7c19b578.ngrok-free.app/continuum/:splat"
  status = 200

[[redirects]]
  from = "/symbolic/*"
  to   = "https://ca8f7c19b578.ngrok-free.app/symbolic/:splat"
  status = 200

[[redirects]]
  from = "/shadow/*"
  to   = "https://ca8f7c19b578.ngrok-free.app/shadow/:splat"
  status = 200

[[redirects]]
  from = "/memory/*"
  to   = "https://web-production-ea504.up.railway.app/:splat"
  status = 200